### ISSUE TITLE
Serialization issue

### ISSUE THREAD

**Issue by gabe2code** [gigwage/gigwage-client-node#16]
Hi everyone,
I'm trying to use the library with NestJS and when I receive the response from your end looks fine. The problem is that all of the frameworks serialize the answers that they receive, and when is trying to parse to string an error occurs:
```
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'ClientRequest'
    |     property 'socket' -> object with constructor 'TLSSocket'
    --- property '_httpMessage' closes the circle
    at JSON.stringify (<anonymous>)
```

Steps to reproduce with Express:

```
 client.get("api/v1/contractors",
 ).then(r => console.log(JSON.stringify(r))).catch(err => console.error(err));
```

Steps to reproduce with NestJS:

1. Import the client and configure it
2. call get contractors (or any request)

Any suggestions to fix that issue?
Best regards

**Comment by harryhorton** [comment]
Hi, @gabe2code 👋 Thanks for the repot!

The client http methods will return a response object, not just the data. We're currently working on a new API that will provide methods and types for all the queries and return just the data.

Try getting the information you're looking for from `r.data` for now.

**Comment by harryhorton** [comment]
Hi @gabe2code, we just created a [beta release](https://github.com/gigwage/gigwage-client-node/releases/tag/v1.2.0-beta.0) of the Gig Wage client. This version of the client has methods and types for every non-partner/business endpoint, which should hopefully make the API a lot easier to consume!
